<?php

/**
 * @file
 * private_comments.module
 * Allows users to choose if the comment should be public (published to the site), or pivate (sent to the site moderator)
 */


/** 
 * do not publish private comments
 * - check if configuration set for specific content types
 * - we would like to unpublish comments for selected content types if is_public checkbox is checked
 * - is_public field supposed to be on the comments form for the selected content types
 */ 
function private_comments_comment_presave($comment) { 
	$content_types = variable_get('private_comments_node_types');
	$node_type = $comment->node_type;
	$node_type = str_replace('comment_node_', '', $node_type);

	if(!empty($content_types[$node_type])){
		$status = $comment->is_public['und'][0]['value'];
		if($status!="1"){
			$comment->status = "0";
			$_SESSION['comment_published'] = "0";
			//watchdog("private_comments", 'setting comment status to %status', array('%status' => print_r($comment, true)));
		}
	}
}
/*
function private_comments_comment_insert($comment) {
	unset($_SESSION['messages']);
	 drupal_set_message(t('override like this.'));
}
*/


//alter submit comments form for selected content types
function private_comments_form_alter(&$form, $form_state, $form_id) {
	$content_types = variable_get('private_comments_node_types');
						
	foreach($content_types as $content_type_key => $content_type_val){
		if(!empty($content_type_val) && $form_id == "comment_node_{$content_type_key}_form" ){
			$form['#submit'][] = 'private_comments_comments_form_submit';
			break;
		}
	}
}
function private_comments_comments_form_submit($form, &$form_state){

	//if comment is pivate we clear the messages and display a new message

	if(isset($_SESSION['comment_published']) &&  $_SESSION['comment_published'] == "0"){
		unset($_SESSION['messages']);
		unset($_SESSION['comment_published']);
		drupal_set_message("Your comment has been sent to the site moderator and will remain private.");
	}
}


/**
* Implementation of hook_menu().
*/
function private_comments_menu() {
  $items['admin/config/private_comments'] = array(
    'title' => 'private comments',
    'description' => 'Adjust private comments options.',
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/private_comments/settings'] = array(
    'title' => 'private comments settings',
    'description' => 'Change private comments options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('private_comments_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'private_comments.admin.inc',
  );
  return $items;
}

