<?php

/**
 * @mainpage Subscriptions module
 *
 * This module enables users to subscribe to be notified of changes to nodes or
 * taxonomies, such as new comments in specific forums, or additions to some
 * category of blog. Once enabled, all nodes will have an additional link that
 * allows the user to change their subscriptions. Users get a tab on their user
 * page to manage their own subscriptions. Users can also set an auto-subscribe
 * function which notifies the user if anyone comments on posts they have made.
 * Admins can turn this on by default.
 */

/**
 * @file
 * Subscriptions module.
 */

/**
 * Implements hook_init().
 *
 * @ingroup hooks
 * @ingroup init
 */
function subscriptions_init() {
  define('SUBSCRIPTIONS_UNAVAILABLE', '<span class="error" title="' . t('(unavailable to regular users)') . '">&curren;</span>');
  if (arg(0) == 'subscriptions' || arg(2) == 'subscriptions') {
    include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'subscriptions') . '/subscriptions.admin.inc'; // TODO: do we need this?
  }
  if (arg(0) == 's' && arg(1) == 'del') {
    $router_item = menu_get_item('subscriptions/rem/' . substr($_GET['q'], 6));
    if (isset($router_item) && $router_item['access']) {
      menu_set_item($_GET['q'], $router_item);
    }
  }
}

/**
 * Implements hook_menu().
 *
 * @ingroup hooks
 * @ingroup menu
 */
function subscriptions_menu() {
  global $user;  // we need the user to to build some urls

  $items['admin/config/subscriptions'] = array(
    'title' => 'Subscriptions',
    'description' => 'Site and user default settings for Subscriptions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('subscriptions_settings_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/subscriptions/settings'] = array(
    'title' => 'Site settings',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/subscriptions/userdefaults'] = array(
    'title' => 'User defaults',
    'weight' => -5,
    'page callback' => 'subscriptions_page_user_overview',
    'page arguments' => array(NULL),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/subscriptions/userdefaults/settings'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Overview',
    'weight' => -100,
  );
  $items['admin/config/subscriptions/intervals'] = array(
    'title' => 'Interval',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('subscriptions_intervals'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );
  $items['user/%user/subscriptions'] = array(
    'title' => 'Subscriptions',
    'page callback' => 'subscriptions_page_user_overview',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => '_subscriptions_access',
    'access arguments' => array(1),
  );

  $hide_overview_page = variable_get('subscriptions_hide_overview_page', 0);
  if (!$hide_overview_page) {
    $items['user/%user/subscriptions/overview'] = array(
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'title' => 'Overview',
      'weight' => -100,
    );
  }
  else {
    $minimum_weight = 0;
    foreach (subscriptions_types() as $stype => $data) {
      if (isset($data['weight']) && $data['weight'] < $minimum_weight) {
        $minimum_weight = $data['weight'];
      }
    }
  }

  foreach (subscriptions_types() as $stype => $data) {
    $weight = (isset($data['weight']) ? $data['weight'] : 0);
    $items['subscriptions/add/' . $stype] = array(
      'title' => 'Add subscription',
      'type' => MENU_CALLBACK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('subscriptions_add_form', $stype),
      'access arguments' => array($data['access']),
    );
    $items['subscriptions/del/' . $stype] = array(
      'type' => MENU_CALLBACK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('subscriptions_del_form', $stype),
      'access arguments' => array($data['access']),
    );

    if (empty($data['page'])) {
      continue;  // no page
    }
    $items['user/%user/subscriptions/' . $stype] = array(
      'title' => $data['title'],
      'type' => MENU_LOCAL_TASK,
      'file' => 'subscriptions.admin.inc',
      'page callback' => 'subscriptions_page',
      'page arguments' => array(1, $stype),
      'access callback' => '_subscriptions_access',
      'access arguments' => array(1, $data['access']),
      'weight' => $weight,
    );

    if ($hide_overview_page && $minimum_weight == $weight) {
      // Install the first subscription type page as the default task.
      $items['user/%user/subscriptions/' . $stype]['type'] = MENU_DEFAULT_LOCAL_TASK;
      $default_item = $items['user/%user/subscriptions/' . $stype];
      $items['user/%user/subscriptions'] = array_merge($items['user/%user/subscriptions'], array(
        'file' => $default_item['file'],
        'page callback' => $default_item['page callback'],
        'page arguments' => $default_item['page arguments'],
        'access callback' => $default_item['access callback'],
        'access arguments' => $default_item['access arguments'],
      ));
      $hide_overview_page = FALSE;
    }

    if ($stype == 'node') {
      continue;  // not in site settings
    }
    $items['admin/config/subscriptions/userdefaults/' . $stype] = array(
      'title' => $data['title'],
      'type' => MENU_LOCAL_TASK,
      'file' => 'subscriptions.admin.inc',
      'page callback' => 'subscriptions_page',
      'page arguments' => array(NULL, $stype),
      'access arguments' => array('administer site configuration'),
      'weight' => $weight,
    );
  }

  // Unsubscribe links
  $items['subscriptions/rem/%'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('subscriptions_delete_form', 2, 3, 4, 5, 6),
    'type' => MENU_CALLBACK,
    'access callback' => '_subscriptions_rem_access',
    'access arguments' => array(2, 3, 4, 5, 6, 7),
  );
  return $items;
}

function _subscriptions_rem_access($a2, $a3, $a4, $a5, $a6, $md) {
  return $md == md5(drupal_get_private_key() . $a2 . $a3 . $a4 . $a5 . $a6);
}

function _subscriptions_access($account, $access = NULL) {
  global $user;
  if ($account && $account->uid) {
    if (isset($access)) {
      $has_access = user_access($access, $account);
    }
    else {
      foreach (subscriptions_types() as $stype => $data) {
        if (user_access($data['access'], $account)) {
          $has_access = TRUE;
        }
      }
    }
    return !empty($has_access) && ($account->uid == $user->uid || user_access('administer user subscriptions'));
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 *
 * @ingroup hooks
 */
function subscriptions_permission() {
  $placeholder_key = 'subscribe to all content types';
  $return = array_merge(
    array(
      'administer user subscriptions' => array(
        'title' => t('Administer user subscriptions'),
        'description' => t('Administer the subscriptions of all other users.'),
        'restrict access' => TRUE,
      ),
      $placeholder_key => array(),
    ),
    subscriptions_types('permission'),
    array(
      'suspend own subscriptions' => array(
        'title' => t('Suspend own subscriptions'),
        'description' => t('Allow suspending &mdash; resuming is always allowed.'),
      ),
    )
  );
  if (!$return[$placeholder_key]) {
    unset($return[$placeholder_key]);
  }
  return $return;
}

/**
 * Implements hook_user_insert().
 *
 * Set up the Subscriptions defaults for the new user.
 *
 * @ingroup hooks
 */
function subscriptions_user_insert($edit, &$account, $category) {
  $new_uid = &drupal_static('subscriptions_user_insert', 0);
  db_insert('subscriptions_user')
    ->fields(array(
      'uid' => $account->uid,
    ))
    ->execute();
  // $account->roles isn't set yet, subscriptions_user_load() below will
  // insert the role-specific initial subscriptions.
  $new_uid = $account->uid;
}

/**
 * Implements hook_user_load().
 *
 * Set the role-specific initial subscriptions for new users (continued
 * from subscriptions_user_insert() above).
 *
 * @ingroup hooks
 */
function subscriptions_user_load($users) {
  $new_uid = &drupal_static('subscriptions_user_insert', 0);
  if ($new_uid && isset($users[$new_uid])) {
    foreach (array_keys($users[$new_uid]->roles) as $rid) {
      $rids[] = -$rid;
    }
    $query = db_select('subscriptions', 's')
      ->fields('s', array('module', 'field', 'value'));
    $query->addExpression($new_uid, 'recipient_uid');
    $query
      ->fields('s', array('send_interval', 'author_uid', 'send_updates', 'send_comments'))
      ->condition('s.recipient_uid', $rids, 'IN');
    db_insert('subscriptions')
      ->from($query)
      ->execute();
    $new_uid = 0;
  }
}

/**
 * Implements hook_user_delete().
 *
 * @ingroup hooks
 */
function subscriptions_user_delete($account) {
  db_delete('subscriptions_user')
    ->condition('uid', $account->uid)
    ->execute();
  db_delete('subscriptions')
    ->condition('recipient_uid', $account->uid)
    ->execute();
  db_delete('subscriptions_last_sent')
    ->condition('uid', $account->uid)
    ->execute();
}

/**
 * Helper function to do access checking and create a subscription.
 */
function subscriptions_write($access_key, $module, $field, $value, $author_uid = -1, $recipient = NULL, $send_interval = 1, $send_updates = 0, $send_comments = 0) {
  global $user;
  // Access checking
  $recipient_uid = isset($recipient) ? $recipient : $user->uid;
  $access = subscriptions_types('access', $access_key);
  if ($recipient_uid && $access && ($recipient_uid == $user->uid && user_access($access) || user_access('administer user subscriptions')) || $recipient_uid == 0 && user_access('administer site configuration')) {
    subscriptions_write_subscription($module, $field, $value, $author_uid, $recipient_uid, $send_interval, $send_updates, $send_comments);
  }
}

/**
 * Queue events for notifications.
 *
 * @param $event
 *   Event array.
 */
function subscriptions_queue($event) {
  global $user;

  if (isset($event['node']->nid) && strpos('  ' . variable_get('subscriptions_blocked_nodes', '') . ' ', ' ' . $event['node']->nid . ' ')) {
    return;
  }

  $event += array(
    'uid' => $user->uid,
    'load_args' => '',
  );

  foreach (module_implements('subscriptions_queue_alter') as $module) {
    $function = $module . '_subscriptions_queue_alter';
    $function($event);
    if (empty($event)) {
      return;  // $event was cleared, forget it
    }
  }

  if (is_array($event['load_args'])) {
    $event['load_args'] = serialize($event['load_args']);
  }
  if (!empty($event['noqueue_uids'])) {
    // Allow hook_subscriptions_queue_alter() modules to set uids that won't get any notifications queued:
    $noqueue_uids_where = "s.recipient_uid NOT IN (" . implode(', ', array_fill(0, count($event['noqueue_uids']), '%d')) . ")";
  }

  foreach (module_implements('subscriptions') as $subs_module) {
    $subs_module_query = module_invoke($subs_module, 'subscriptions', 'queue', $event);
    if (!isset($subs_module_query)) {
      continue;
    }
    foreach ($subs_module_query as $module => $module_query) {
      foreach ($module_query as $field => $query) {
        //TODO: if any of $join, $where, $args are assigned, this doesn't work!
        //$join = empty($query['join']) ? '' : $query['join'];
        //$where = empty($query['where']) ? array() : array($query['where']);
        //if (!empty($query['args'])) {
        //  $args = array_merge($args, $query['args']);
        //}
        //$conditions = implode(' AND ', $where);
        //$sql = "
        //  INSERT INTO {subscriptions_queue} (uid, name, language, module, field, value, author_uid, send_interval, digest, last_sent, load_function, load_args, is_new, suspended)
        //  SELECT u.uid, u.name, u.language, s.module, s.field, s.value, s.author_uid, s.send_interval, su.digest, COALESCE(sls.last_sent, 0), '%s', '%s', '%d', suspended
        //  FROM {subscriptions} s
        //  INNER JOIN {subscriptions_user} su ON s.recipient_uid = su.uid
        //  INNER JOIN {users} u ON su.uid = u.uid
        //  $join
        //  LEFT JOIN {subscriptions_last_sent} sls ON su.uid = sls.uid AND s.send_interval = sls.send_interval
        //  WHERE
        //    s.module = '%s' AND
        //    s.field = '%s' AND
        //    s.author_uid IN (%d, -1) AND $conditions";

        $select = db_select('subscriptions', 's');
        $select->innerJoin('subscriptions_user', 'su', 's.recipient_uid = su.uid');
        $select->innerJoin('users', 'u', 'su.uid = u.uid');
        $select->leftJoin('subscriptions_last_sent', 'sls', 'su.uid = sls.uid AND s.send_interval = sls.send_interval');
        if (!empty($query['join'])) {
          $alias = $select->innerJoin($query['join']['table'], $query['join']['alias'], $query['join']['on']);
        }
        $select
          ->fields('u', array('uid', 'name', 'language'))
          ->fields('s', array('module', 'field', 'value', 'author_uid', 'send_interval'))
          ->fields('su', array('digest', 'suspended'));
        $select->addExpression('COALESCE(sls.last_sent, 0)', 'last_sent');
        $select->addExpression("'" . $event['load_function'] . "'", 'load_function');
        $select->addExpression("'" . $event['load_args'] . "'", 'load_args');
        $select->addExpression((int) $event['is_new'], 'is_new');
        $select
          ->condition('s.module', $module)
          ->condition('s.field', $field)
          // author-specific subscriptions trigger on comments, when the node author is subscribed to:
          ->condition('s.author_uid', array(($module == 'node' && $event['type'] == 'comment' && isset($event['node']->uid) ? $event['node']->uid : $event['uid']) , -1), 'IN')
          ->groupBy('u.uid');

        if (!empty($query['where'])) {
          foreach ($query['where'] as $cond) {
            $select->condition($cond[0], $cond[1], $cond[2]);
          }
        }

        if (!empty($query['value'])) {
          $select
            ->condition('s.value', $query['value']);
        }

        if ($user->uid && !_subscriptions_get_setting('send_self', $user)) {
          $select
            ->condition('s.recipient_uid', $user->uid, '<>');
        }
        if (!empty($event['noqueue_uids'])) {
          // Allow hook_subscriptions_queue_alter() modules to set uids that won't get any notifications queued:
          $select
            ->condition('s.recipient_uid', $event['noqueue_uids'], 'NOT IN');
        }
        if (!empty($query['groupby'])) {
          $select
            ->groupBy($query['groupby']);
        }
        $insert = db_insert('subscriptions_queue')
          ->from($select);
        $sqid = $insert->execute();
        /*  for debugging:
        drupal_set_message($insert->__toString() . '<br />ID=' . $sqid . ' inserted.');
        /**/
      }
    }
  }
}

/**
 * Get subscription sid for the given parameters.
 */
function subscriptions_get_subscription($uid, $module, $field, $value, $author_uid = -1) {
  static $subscriptions;

  if (!isset($subscriptions[$uid][$module][$field][$value][$author_uid])) {
    $subscriptions[$uid][$module][$field][$value][$author_uid] = db_query("SELECT sid FROM {subscriptions} WHERE module = :module AND field = :field AND value = :value AND author_uid = :author_uid AND recipient_uid = :recipient_uid", array(
      ':module' => $module,
      ':field' => $field,
      ':value' => $value,
      ':author_uid' => $author_uid,
      ':recipient_uid' => $uid
    ))->fetchField();
  }

  return $subscriptions[$uid][$module][$field][$value][$author_uid];
}

/**
 * Get all subscription fields for the given parameters.
 */
function subscriptions_get_full_subscription($uid, $module, $field, $value, $author_uid = -1) {
  $sql = "SELECT * FROM {subscriptions} WHERE module = '%s' AND field = '%s' AND value = '%s' AND author_uid = %d AND recipient_uid = %d";
  return db_fetch_object(db_query("SELECT * FROM {subscriptions} WHERE module = :module AND field = :field AND value = :value AND author_uid = :author_uid AND recipient_uid = :recipient_uid", array(
    ':module' => $module,
    ':field' => $field,
    ':value' => $value,
    ':author_uid' => $author_uid,
    ':recipient_uid' => $uid
  )));
}

/**
 * Create a subscription.
 */
function subscriptions_write_subscription($module, $field, $value, $author_uid, $recipient_uid, $send_interval = 1, $send_updates = 0, $send_comments = 0) {
  db_merge('subscriptions')
    ->key(array(
      'module'        => $module,
      'field'         => $field,
      'value'         => $value,
      'recipient_uid' => $recipient_uid,
      'author_uid'    => $author_uid,
    ))
    ->fields(array(
      'send_interval' => $send_interval,
      'send_updates'  => ($send_updates ? 1 : 0),
      'send_comments' => ($send_comments ? 1 : 0),
    ))
    ->execute();
}

/**
 * Provide the form definition for deleting subscriptions via
 * s/del/... (aka subscriptions/rem/...) link.
 *
 * Callback of _subscriptions_menu().
 *
 * @param $form_state
 *   FAPI form state.
 * @param $module
 *   Module that controls the subscription.
 * @param $field
 *   Field that controls the subscription (subscription type).
 * @param $value
 *   Subscription parameter (depends on type).
 * @param $author_uid
 *   User ID for author-specific subscriptions or -1/NULL for all authors.
 * @param $recipient_uid
 *   User ID of the subscriber.
 *
 * @ingroup forms
 * @see _subscriptions_menu()
 */
function subscriptions_delete_form($form, &$form_state, $module, $field, $value, $author_uid, $recipient_uid) {
  $form['data'] = array('#type' => 'value', '#value' => array($module, $field, $value, $author_uid, $recipient_uid));
  // We might be called from subscriptions_del_form() and don't want to submit to subscriptions_del_form_submit():
  $form['#submit'][] = 'subscriptions_delete_form_submit';
  return confirm_form($form, t('Are you sure you want to unsubscribe?'), '<front>', NULL, t('Unsubscribe'));
}

/**
 * Delete Subscription form submit handler.
 */
function subscriptions_delete_form_submit($form, &$form_state) {
  db_delete('subscriptions')
    ->condition('module', $form_state['values']['data']['0'])
    ->condition('field', $form_state['values']['data']['1'])
    ->condition('value', $form_state['values']['data']['2'])
    ->condition('author_uid', $form_state['values']['data']['3'])
    ->condition('recipient_uid', $form_state['values']['data']['4'])
    ->execute();
  drupal_set_message(t('Your subscription was deactivated.'));
  $form_state['redirect'] = '<front>';
}

/**
 * Subscribe users to content they post, if not already subscribed
 * (context: on_post, on_update, on_comment).
 */
function subscriptions_autosubscribe($module, $field, $value, $context) {
  global $user;
  // if user has auto subscribe enabled and he's not already subscribed
  if ($user->uid && _subscriptions_get_setting('autosub_' . $context, $user) && !subscriptions_get_subscription($user->uid, $module, $field, $value)) {
    subscriptions_write_subscription($module, $field, $value, -1, $user->uid, _subscriptions_get_setting('send_interval', $user), 1, 1);
  }
}

/**
 * Get subscriptions.
 *
 * @param $params
 *   Array of parameters for the query.
 * @return
 *   Array of subscriptions indexed by uid, module, field, value, author_uid.
 */
function subscriptions_get($params) {
  $subscriptions = array();
  // Build query
  $query = db_select('subscriptions', 's');
  foreach ($params as $field => $value) {
    $query->condition($field, $value);
  }
  foreach ($query->execute() as $s) {
    $subscriptions[$s->recipient_uid][$s->module][$s->field][$s->value][$s->author_uid] = 1;
  }
  return $subscriptions;
}

/**
 * Hook subscription_types(). Get info about subscription types.
 *
 * @return
 *   Information for a given field and type
 *   or information for a given field for all types
 *
 * @ingroup hooks
 */
function subscriptions_types($field = NULL, $type = NULL) {
  static $types, $list;

  if (!isset($types)) {
    $types = module_invoke_all('subscriptions', 'types');
    foreach ($types as $stype => $data) {
      if (!_subscriptions_validate_hook_result($stype, $data)) {
        continue;
      }
      foreach ($data as $name => $value) {
        $list[$name][$stype] = $value;
      }
    }
  }
  if ($type) {
    return isset($types[$type][$field]) ? $types[$type][$field] : NULL;
  }
  elseif ($field) {
    if ($field == 'permission' && isset($list['access']) && is_array($list['access'])) {
      $result = array();
      foreach ($list['access'] as $type => $access) {
        if (isset($list['permission'][$type]) && is_array($list['permission'][$type])) {
          $result[$access] = $list['permission'][$type];
        }
      }
      return $result;
    }
    return isset($list[$field]) ? $list[$field] : array();
  }
  else {
    return $types;
  }
}

/**
 * Check return values of hook_subscriptions().
 */
function _subscriptions_validate_hook_result($stype, $data) {
  if (isset($stype)) {
    if (!is_numeric($stype) && is_array($data) && isset($data['title']) && isset($data['access']) &&
      ($data['title'] === '' || isset($data['page']) && isset($data['fields']) && is_array($data['fields']))) {
      return TRUE;
    }
  }

  static $already_reported = FALSE;
  if (!$already_reported) {
    $already_reported = TRUE;
    foreach (module_implements('subscriptions') as $module) {
      $hook = $module . '_subscriptions';
      $types = $hook('types');
      foreach ($types as $stype => $data) {
        if (!_subscriptions_validate_hook_result($stype, $data)) {
          $modules[$module] = $module;
        }
      }
    }
    drupal_set_message(t('The following modules return invalid data from %hook: !modules   Either they are buggy !Subscriptions add-ons, or they are unrelated to !Subscriptions and should not define %hook!', array('%hook' => 'hook_subscriptions()', '!modules' => '<ul><li>' . implode($modules, '</li><li>') . '</li></ul>', '!Subscriptions' => 'Subscriptions')), 'error', FALSE);
  }
  return FALSE;
}

/**
 * Implements hook_theme().
 */
function subscriptions_theme() {
  return array(
    'subscriptions_form_table' => array(
      'file' => 'subscriptions.admin.inc',
      'render element' => 'element',
    )
  );
}

/**
 * Returns TRUE if the given $nid is blocked.
 */
function subscriptions_node_is_blocked($nid) {
  return strpos('  ' . variable_get('subscriptions_blocked_nodes', '') . ' ', ' ' . $nid . ' ');
}

/**
 * Helper function for uasort()ing arrays with elements that have a 'weight'
 */
function _subscriptions_cmp_by_weight($a, $b) {
  $a = (isset($a['weight']) ? $a['weight'] : 0);
  $b = (isset($b['weight']) ? $b['weight'] : 0);
  return ($a < $b ? -1 : ($a == $b ? 0 : +1));
}

/**
 * Helper function to retrieve
 *   send_self/autosub_on_post/autosub_on_update/autosub_on_comment/    | 1, 0,
 *   digest/send_interval/send_updates/send_comments/                   | -1 = use default
 *   send_interval_visible/send_updates_visible/send_comments_visible/  | 1, 0, -1 = only preference, -2 = always use site default
 *   uses_defaults values;
 * $account can be NULL/0 (for site default), a user object, or a uid.
 */
function _subscriptions_get_setting($name, $account) {
  global $user;
  if (!isset($account) || is_object($account) && empty($account->uid) || is_numeric($account) && $account <= 0 ) {
    $uid = -DRUPAL_AUTHENTICATED_RID;
    unset($account);
  }
  elseif (is_numeric($account)) {
    if ($account == $user->uid) {
      $account = $user;
      $uid = $user->uid;
    }
    else {
      $uid = $account;
      unset($account);
    }
  }
  if (isset($account)) {
    $uid = $account->uid;
  }

  static $defaults = array();
  if (!isset($defaults[$uid][$name])) {
    $result = db_select('subscriptions_user', 'su', array('fetch' => PDO::FETCH_ASSOC))
      ->fields('su', array('uid', 'digest', 'send_interval', 'send_updates', 'send_comments', 'send_interval_visible', 'send_updates_visible', 'send_comments_visible', 'autosub_on_post', 'autosub_on_update', 'autosub_on_comment', 'send_self'))
      ->condition('su.uid', array(-DRUPAL_AUTHENTICATED_RID, $uid), 'IN')
      ->orderBy('su.uid')
      ->execute();
    foreach ($result as $s) {
      $defaults[$s['uid']] = $s;
    }
    if (empty($defaults[$uid])) {
      // Note: This should not happen -- subscriptions_user_insert() and
      // subscriptions_user_delete() take care of inserting/removing records
      // as users are created/deleted.
      // If it does happen, then users were created without calling the proper
      // hooks, or they may have been created on another multi-site (#351753).
      // Let's add the missing records, as if the user were being created just
      // now, with the expected hook_user() invocations:
      $account = user_load($uid);
      subscriptions_user_insert(NULL, $account, NULL);
      subscriptions_user_load(array($account->uid => $account));
      return _subscriptions_get_setting($name, $account);
    }
    $defaults[$uid]['uses_defaults'] = FALSE;
    foreach ($defaults[$uid] as $key => $value) {
      if ($value < 0) {  // not set, use site dft
        $defaults[$uid][$key] = $defaults[-DRUPAL_AUTHENTICATED_RID][$key];
        $defaults[$uid]['uses_defaults'] = TRUE;
      }
    }
    foreach (array('interval', 'updates', 'comments') as $parm ) {
      // Site overrides user values.
      if ($defaults[-DRUPAL_AUTHENTICATED_RID]['send_' . $parm . '_visible'] == -2) {
        $defaults[$uid]['send_' . $parm] = $defaults[-DRUPAL_AUTHENTICATED_RID]['send_' . $parm];
      }
    }
  }
  return $defaults[$uid][$name];
}

/**
 * Returns whether notifications are suspended for the given user,
 * and optionally alert the user if delivery is suspended.
 */
function subscriptions_suspended($uid, $alert = FALSE) {
  $result = db_query("SELECT suspended FROM {subscriptions_user} WHERE uid = :uid", array(':uid' => $uid))->fetchField();
  if ($result && $alert && empty($_POST)) {
    include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'subscriptions') . '/subscriptions.admin.inc';
    _subscriptions_suspended_alert($uid, $result);
  }
  return $result;
}

/**
 * Implements hook_form_alter().
 *
 * Display a message on user/uid/edit form if subscriptions notifications
 * are suspended.
 *
 * @ingroup hooks
 */
function subscriptions_form_user_profile_form_alter(&$form, &$form_state) {
  subscriptions_suspended(arg(1), TRUE);
}

